# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Webbyappy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ece4263a58e49e4b19b26806b3e09ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_98c558380ceb4f0890a67ee27b51bb5b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/myacr/myapp:latest
        file: ./Docker/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Webbyappy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2fad66d89890472580767c8d3071406a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4ece4263a58e49e4b19b26806b3e09ea }}/appsvc/staticsite:${{ github.sha }}'